### ISSUE TITLE
一直生成失败，这是啥还有python问题？

### ISSUE THREAD

**Issue by jangozw** [xxjwxc/gormt#19]
```

goroutine 1 [running]:
github.com/xxjwxc/gormt/data/view/model.getTypeName(0xc000028cb0, 0x8, 0x1570c25, 0x1)
	/Users/Django/www/tools/gormt/data/view/model/common.go:47 +0x218
github.com/xxjwxc/gormt/data/view/model.(*_Model).genTableElement(0xc000565cd0, 0xc000238700, 0x7, 0x8, 0xc000551180, 0xb, 0x10)
	/Users/Django/www/tools/gormt/data/view/model/model.go:46 +0xc39
github.com/xxjwxc/gormt/data/view/model.(*_Model).generate(0xc000565cd0, 0xc00016a092, 0x5)
	/Users/Django/www/tools/gormt/data/view/model/model.go:29 +0x1fa
github.com/xxjwxc/gormt/data/view/model.Generate(...)
	/Users/Django/www/tools/gormt/data/view/model/model.go:19
github.com/xxjwxc/gormt/data/view/gtools.Execute()
	/Users/Django/www/tools/gormt/data/view/gtools/gtools.go:25 +0x148
github.com/xxjwxc/gormt/data/cmd.glob..func1(0x1a285c0, 0x1a6ce10, 0x0, 0x0)
	/Users/Django/www/tools/gormt/data/cmd/cmd.go:27 +0x20
github.com/spf13/cobra.(*Command).execute(0x1a285c0, 0xc000094010, 0x0, 0x0, 0x1a285c0, 0xc000094010)
	/Users/Django/www/GOPATH/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1a285c0, 0x0, 0x0, 0x0)
	/Users/Django/www/GOPATH/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/Django/www/GOPATH/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/xxjwxc/gormt/data/cmd.Execute()
	/Users/Django/www/tools/gormt/data/cmd/cmd.go:35 +0x2d
main.main()
	/Users/Django/www/tools/gormt/main.go:6 +0x20
```

**Comment by xxjwxc** [comment]
可以加个联系方式吗？具体我看下问题。这个里面似乎看不到问题所在？
或者是当前目录是否有个err文件？
