### ISSUE TITLE
type (float unsigned) not match in any way.maybe need to add on

### ISSUE THREAD

**Issue by xiusin** [xxjwxc/gormt#53]
```
panic: type (float unsigned) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

goroutine 1 [running]:
github.com/xxjwxc/gormt/data/view/model.getTypeName(0xc0003b8ee0, 0xe, 0x15e4806, 0x1)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/common.go:61 +0x218
github.com/xxjwxc/gormt/data/view/model.(*_Model).genTableElement(0xc0002edc78, 0xc000191800, 0xb, 0x11, 0xc00039e380, 0x8, 0x8)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:83 +0xcff
github.com/xxjwxc/gormt/data/view/model.(*_Model).GetPackage(0xc0002edc78, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:55 +0x25c
github.com/xxjwxc/gormt/data/view/model.(*_Model).generate(0xc0002edc78, 0xcea, 0xc0001b9158)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:67 +0x3e
github.com/xxjwxc/gormt/data/view/model.Generate(0xc0001b9198, 0x8, 0xc0001b8e5a, 0x6, 0xc000300000, 0x46, 0x87, 0x87, 0x0, 0x1602672, ...)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:31 +0xc3
github.com/xxjwxc/gormt/data/view/gtools.showCmd()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:37 +0xb7
github.com/xxjwxc/gormt/data/view/gtools.Execute()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:22 +0x38
github.com/xxjwxc/gormt/data/cmd.glob..func1(0x1b1ba60, 0x1b6f408, 0x0, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:32 +0x20
github.com/spf13/cobra.(*Command).execute(0x1b1ba60, 0xc00001e1b0, 0x0, 0x0, 0x1b1ba60, 0xc00001e1b0)
        /Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1b1ba60, 0x0, 0x0, 0x0)
        /Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/xxjwxc/gormt/data/cmd.Execute()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:40 +0x2d
main.main()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/main.go:6 +0x20

```

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go

中添加类型映射，欢迎pr更新

**Comment by xiusin** [comment]
@xxjwxc 感谢这个项目， 我生成的文件里， 如果字段名字为`type` 会有问题
`func (obj *_MaterialMgr) WithType(type string) Option` , type string就变成了重新定义类型了😂

**Comment by xxjwxc** [comment]
这个问题确实存在

**Comment by xxjwxc** [comment]
> @xxjwxc 感谢这个项目， 我生成的文件里， 如果字段名字为`type` 会有问题
> `func (obj *_MaterialMgr) WithType(type string) Option` , type string就变成了重新定义类型了😂

这个问题已经修复了。请更新最新版本
