### ISSUE TITLE
panic: type (double unsigned zerofill) not match in any way.maybe need to add on 

### ISSUE THREAD

**Issue by sgzwiz** [xxjwxc/gormt#90]
panic: type (double unsigned zerofill) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

goroutine 1 [running]:
github.com/xxjwxc/gormt/data/view/model.getTypeName(0xc0003d87a0, 0x18, 0xa31c00, 0x1, 0xa31cc3)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/common.go:71 +0x57f
github.com/xxjwxc/gormt/data/view/model.(*_Model).genTableElement(0xc00041bc20, 0xc0003ff000, 0x1d, 0x22, 0x6, 0x6, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:84 +0xea5
github.com/xxjwxc/gormt/data/view/model.(*_Model).GetPackage(0xc00041bc20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:55 +0x271
github.com/xxjwxc/gormt/data/view/model.(*_Model).generate(0xc00041bc20, 0xc0001d1920, 0x9)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:67 +0x45
github.com/xxjwxc/gormt/data/view/model.Generate(0xc0001d1940, 0x4, 0xc0001d15a2, 0xc, 0xc00045c000, 0x9e, 0x11c, 0x11c, 0xc00038c5d0, 0xa32d30, ...)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:31 +0xaa
github.com/xxjwxc/gormt/data/view/gtools.showCmd()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:51 +0x13f
github.com/xxjwxc/gormt/data/view/gtools.Execute()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:24 +0x3e
github.com/xxjwxc/gormt/data/cmd.glob..func1(0xea3f20, 0xf004d8, 0x0, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:22 +0x27
github.com/spf13/cobra.(*Command).execute(0xea3f20, 0xc00011a010, 0x0, 0x0, 0xea3f20, 0xc00011a010)
        /Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xea3f20, 0x0, 0x0, 0x0)
        /Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/xxjwxc/gormt/data/cmd.Execute()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:30 +0x34
main.main()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/main.go:6 +0x27

**Comment by xxjwxc** [comment]
请看提示

type (double unsigned zerofill) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

请添加double unsigned zerofill
欢迎提mr完善类型
